[package]
name = "sleep_server"
version = "0.1.0"
authors = ["Aleksey Fedotov <0xc0dec@gmail.com>"]

[dependencies]
winapi = "0.2.7"
kernel32-sys = "0.2.2"
user32-sys = "0.2.0"
advapi32-sys = "0.2.0"
iron = "0.3.0"
